config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :comments
  resources :likes
  resources :users#, only: [:new, :create, :show, :edit, :update]
  resources :relationships

  root 'users#new'

  get '/users/:id/followers', to: 'users#followers', as: 'followers'
  get '/users/:id/following', to: 'users#following', as: 'following'

  get "signup", to: "users#new", as: "signup"
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"

  delete "sessions", to: "sessions#destroy", as: "logout"


  # post '/posts/', to: 'posts#like', as: 'likes'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_attached_file :avatar, styles: { thumb: "77x77>", real_small: "77x77>"  }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates :username, :password, :avatar, presence: true


  def following?(user_id)
    if self.active_relationships.find_by(followed_id: user_id) != nil
      true
    else
      false
    end
  end

  def follow!(user_id)
    self.active_relationships.create(followed_id: user_id)
  end

  def unfollow!(user_id)
    self.active_relationships.find_by(followed_id: user_id).destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :show, :edit, :update]
  before_action :set_user
  skip_before_action :set_user, only: [:followers, :following]

  def index
      # byebug
      if params[:search]
        @users = User.all.select do |user|
           user.username == params[:search]
        end
      else
        @users = User.all
      end
    end

  def show
    if @user.id != params[:id]
      @user = User.find_by(id: params[:id])
      @like = Like.new
    else
      render :show
    end
  end

  def new
    @user = User.new
    render :new
  end

  def create
    # byebug
    @user = User.create(user_params)
    if @user.save
      flash[:notice] = "WELCOME #{@user.username}, your account has been created!"
      session[:logged_in_user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    render :edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your updates have been saved!"
      redirect_to user_path
    else
      flash[:notice] = "Uh oh, please check to see your edits are allowed."
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = "Your account has been deleted. Thanks for using TheGram and we hope to see you back soon!"
    redirect_to login_path
  end


  def followers
    @user = User.find_by(id: params[:id])
    @followers = @user.followers
    # byebug

    render :followers
  end

  def following
    @user = User.find_by(id: params[:id])
    @following = @user.following
    render :following
  end


  private

  def user_params
    params.require(:user).permit(:username, :password, :avatar, :search)
  end

  def set_user
    @user = User.find_by(id: session[:logged_in_user_id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% if !!current_user.active_relationships.find_by(followed_id: @user.id) == true %>
  <% else %>
  <% if current_user.id != @user.id %>
  <%= form_for(current_user.active_relationships.build(followed_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
  <% end %>
  <% else %>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<center>

<%= form_for @user, html: { multipart: true } do |f| %>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <%= msg %><br>
    <% end %>
  </ul>
<% end %>


  <%= f.label :username %>
  <%= f.text_field :username %><br><br>

  <%= f.label :password %>
  <%= f.password_field :password %><br><br>

  <%= f.label "Profile Photo" %>
  <%= f.file_field :avatar %><br><br>

  <%= f.submit %>
<% end %>
</center>

app/views/users/_unfollow.html.erb
<%# if current_user.followers %>

<!-- If currently not following the user -->
<% if !!current_user.active_relationships.find_by(followed_id: @user.id) == false %>

<% else %>
  <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
               html: { method: :delete }) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-large" %>
    <% end %>
<% end %>

app/views/users/edit.html.erb
<center><h2>Edit USER</h2></center>

<%= render partial: "form" %>

app/views/users/followers.html.erb
<center>
<h2><%= "#{@user.username} is followed by:" %></h2>

<ul>
<% @followers.each do |follower| %>
  <%= link_to image_tag(follower.avatar.url(:real_small), class:"avater"), user_path(follower) %> <br> <b><%= link_to follower.username, user_path(follower) %><b><br><br>
<% end %>
</ul>

</center>

app/views/users/following.html.erb
<center>
<h2><%= "#{@user.username} is following:" %></h2>

<ul>
<% @following.each do |following| %>
  <%= link_to image_tag(following.avatar.url(:real_small), class:"avater"), user_path(following) %> <br> <b><%= link_to following.username, user_path(following) %></b><br><br>
<% end %>
</ul>

</center>

app/views/users/index.html.erb
<center><h1>Browse and Search for Users</h1></center>
<center><%= form_tag(users_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search People" %>
    <%= submit_tag "Search" %>
<% end %>

<p>Total users: <%= User.all.count %></p>

<br>
<h3><u>Users</u></h3>

<%# sort alphabetically, must all be lowercase usernames %>
<%# @users = @users.order(:username) %>

<%# sort by creation %>
<% @users = @users.reverse %>
<% @users.each do |everyone| %>
  <%= link_to image_tag(everyone.avatar.url(:real_small), class:"avater"), everyone %> <br> <b><%= link_to everyone.username, everyone  %></b><br><br>
<% end %>
</center>

app/views/users/new.html.erb
<center><h2>New User!</h2>

<h3><%= flash[:notice] %></h3>

<%= render partial: "form" %>

</center>

app/views/users/show.html.erb
<center>
   <%= link_to "Search Users", users_path %>
 <br><br>

 <%= image_tag @user.avatar.url(:thumb), class:"avater"  %> <h2><%= @user.username %> | <%= @user.posts.count %> <%= "Posts" %> | <%= @user.following.count %> <%= link_to "Following", following_path(@user) %> | <%= @user.followers.count %> <%= link_to "Followers", followers_path(@user) %> |<br></h2>


<h3><%= flash[:notice] %></h3>


<% if @user.id == session[:logged_in_user_id] %>
  <%= link_to "New Post", new_post_path %> | | <%= link_to "Edit User", edit_user_path(@user) %> | |
  <%= link_to 'Delete Account', user_path(current_user.id), method: :delete, data: { confirm: 'Are you sure?' } %>
  <br><br><br>
  <% if current_user.following.count == 0 && current_user.posts.count == 0 %>
    <p>Clicking 'TheGram' at the top will take you to the feed.</p>
    <p>Click 'New Post' to post a new photo or 'Search Users' to find accounts to follow. </p>
  <% end %><br>
<% end %>



<!-- TEMPORARILY DELETE THE BELOW RENDER PARTIALS TO BE ABLE TO SEE ALL SHOW PAGES FUNCTIONING -->
<%= render partial: "follow" %>
<%= render partial: "unfollow" %>
<!-- TEMPORARILY DELETE THE ABOVE RENDER PARTIALS TO BE ABLE TO SEE ALL SHOW PAGES FUNCTIONING -->




<% posts = @user.posts.reverse %>
<% posts.each do |post| %>
      <%= link_to image_tag(post.picture.url(:medium), :class => "class_name"), post_path(post); %><br><br>
<%= post.caption %><br>


  <% if post.likes.count == 1 %>
    <%= post.likes.count %> like ||
    <% else %>
    <%= post.likes.count %> likes ||
  <% end %>


  <% if post.comments.count == 1 %>
    <%= post.comments.count %> <%= link_to 'comment', post_path(post) %>
    <% else %>
    <%= post.comments.count %> <%= link_to 'comments', post_path(post) %>
  <% end %>

  <% if current_user.likes.find_by(post_id: post.id) %>
    <div class = "unlike_button">
      <%= form_for @like do |f| %>
        <%= hidden_field_tag "post", post.id  %>
        <%= hidden_field_tag "unlike", "unlike" %>
        <%= hidden_field_tag "user_id", @user.id %>
        <%= f.submit "Unlike!"%><br><br>
      <% end %>
    </div>
  <% end %>

  <% if !current_user.likes.find_by(post_id: post.id) %>
    <div class = "like_button">
      <%= form_for @like do |f| %>
        <%= hidden_field_tag "post", post.id  %>
        <%= hidden_field_tag "like", "like" %>
        <%= hidden_field_tag "user_id", @user.id %>
        <%= f.submit "Like!"%> <br><br>
      <% end %>
    </div>
  <% end %>
<% end %></center>